-- Active: 1667410830254@@127.0.0.1@3306@BELAJAR_CA
CREATE TABLE products(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    code char(50),
    name VARCHAR(200),
    price int,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT '';